Trigger build by tag commit (#66)
* Trigger build from tag commit

* rename job

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,8 +1,14 @@
 # actionscore/cli build pipeline
 
+# Release process - https://github.com/actionscore/actions/wiki/Release-Process
+
 trigger:
-- master
-- release-*
+  branches:
+    include:
+    - master
+  tags:
+    include:
+    - v*
 
 variables:
   GOPATH: '$(system.defaultWorkingDirectory)/gopath'
@@ -15,36 +21,27 @@ jobs:
     vmImage: ubuntu-latest
   steps:
     - script: |
-        SOURCEBRANCH=$(Build.SourceBranchName)
+        SOURCEBRANCH=$(Build.SourceBranch)
         echo Source branch name : $SOURCEBRANCH
-        if [[ $SOURCEBRANCH != release-* ]]; then
-          echo Clearing REL_VERSION value unless $SOURCEBRANCH is release-*.
+        if [[ $SOURCEBRANCH != refs/tags/v* ]]; then
+          echo Clearing REL_VERSION value unless $SOURCEBRANCH is refs/tags/v.
           RELVERSION=""
           echo "##vso[task.setvariable variable=REL_VERSION;isOutput=true]$RELVERSION"
           exit 0
         fi
-        BRANCH_VERSION=${SOURCEBRANCH#release-}
-        echo Release branch version : $BRANCH_VERSION
-        
-        RELEASE_VERSION=$(git tag -l "v$BRANCH_VERSION-*" | tail -1)
-        [ -z "$RELEASE_VERSION" ] && echo "Cannot find the release version tag!" && exit 1
-        
-        RELVERSION=${RELEASE_VERSION#v*}
-        echo Release Version in tag : $RELVERSION
+        RELVERSION=${SOURCEBRANCH#refs/tags/v}
+        echo Release version : $RELVERSION
   
         echo "##vso[task.setvariable variable=REL_VERSION;isOutput=true]$RELVERSION"
         echo $RELVERSION > $(Build.ArtifactStagingDirectory)/release_version.txt
         echo $(Build.SourceVersion) > $(Build.ArtifactStagingDirectory)/release_commit_id.txt
 
-        echo Checking release note for $RELVERSION...
-        RELNOTE_PATH="docs/release_notes/v$RELVERSION.md"
-        if [ -f "$RELNOTE_PATH" ]; then
-          echo Found release note $RELNOTE_PATH and copying to artifact directory
-          cp $RELNOTE_PATH $(Build.ArtifactStagingDirectory)/release_note.md
+        if [ "$LATEST_RELEASE" == "true" ]; then
+          echo Checking release note for $RELVERSION...
+          RELNOTE_PATH="docs/release_notes/v$RELVERSION.md"
+          [ ! -f "$RELNOTE_PATH" ] && echo "$RELNOTE_PATH not found" && exit 1
+
           echo Add release tag
-          echo "##vso[build.addbuildtag]release"
-        else
-          echo Skip releasing release note. this is not final release.
           echo "##vso[build.addbuildtag]release"
         fi
       name: env_var_step
@@ -89,9 +86,9 @@ jobs:
     targetArch: arm64
     dependStep: release_environment
     relVersion: $[ dependencies.release_environment.outputs['env_var_step.REL_VERSION'] ]
-- job: 'publish_edge_binaries'
+- job: 'release_to_github'
   pool:
-    vmImage: 'windows-2019'
+    vmImage: ubuntu-latest
   dependsOn:	
     - build_darwin_amd64_actions	
     - build_linux_amd64_actions	
@@ -99,17 +96,26 @@ jobs:
     - build_linux_arm_actions	
     - build_linux_arm64_actions
     - release_environment
-  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
+  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['LATEST_RELEASE'], 'true'))
+  variables:
+    REL_VERSION: $[ dependencies.release_environment.outputs['env_var_step.REL_VERSION'] ]
   steps:
     - task: DownloadPipelineArtifact@2
       inputs:
         buildType: 'current'
         itemPattern: '**/*.zip'
         targetPath: '$(Pipeline.Workspace)'
-    - task: AzureFileCopy@3
+    - task: GitHubRelease@0
+      displayName: 'Upload Actions binaries to GitHub Release'
       inputs:
-          SourcePath: '$(Pipeline.Workspace)/drop'
-          azureSubscription: 'Actions Releases'
-          Destination: 'AzureBlob'
-          storage: 'actionsreleases'
-          ContainerName: 'bin'
+        gitHubConnection: 'GitHub'
+        repositoryName: '$(Build.Repository.Name)'
+        action: 'create'
+        target: '$(Build.SourceVersion)'
+        tagSource: 'manual'
+        tag: 'v$(REL_VERSION)'
+        title: 'Actions Runtime $(REL_VERSION) Release'
+        assets: '$(Pipeline.Workspace)/**'
+        releaseNotesFile: './docs/release_notes/v$(REL_VERSION).md'
+        isPreRelease: true
+        addChangeLog: false
